#DB選択
USE DB001_PMDB;

#T100
DROP TABLE M100_USER;
CREATE TABLE M050_USER (
	USERID char(18) NOT NULL,
    USERNAME varchar(30) ,
    MAIL_ADDRESS varchar(256) ,
    LOGINID varchar(30) ,
    LOGINPASS varchar(1024) ,
    #HYOKA tinyint (2) ,
    USERCOMMENT varchar (2048) ,
    LOGINKBN char(1) NOT NULL,
	CRTSRV char(5) NOT NULL,
	CRTUSR char(18) NOT NULL,
	CRTDATE DATETIME NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR char(18) NOT NULL,
	UPDDATE DATETIME NOT NULL,
	DELFLG char(1) NOT NULL,
    PRIMARY KEY(USERID),
    UNIQUE (LOGINID)
);
