#DB選択
USE PMDB;

#1件
select PROJECTID,SEQ,TASKTITLE,TASKDETAIL,NAIYO,TANTSH,KIHYO_DATE,KIGN_DATE,TASKSTATUS from T110_TASK where PROJECTID = '' and SEQ = 1 and DELFLG = '0' ;

#リスト
select PROJECTID,SEQ,TASKTITLE,TASKDETAIL,NAIYO,TANTSH,KIHYO_DATE,KIGN_DATE,TASKSTATUS from T110_TASK where PROJECTID = '' and DELFLG = '0' order by SEQ ASC ;

#リスト2
select 
	PROJECTID,
	SEQ,
    TASKTITLE,
    TASKDETAIL,
    NAIYO,
    TANTSH,
    KIHYO_DATE,
    KIGN_DATE,
    TASKSTATUS,
    M101.NAIYO01 AS TASKSTATUS_NAME
from T110_TASK T110
LEFT OUTER JOIN M101_HANYOMST M101
	ON T110.TASKSTATUS = M101.CD
    and M101.SECCD = "SEC0001"
    and M101.DELFLG = "0"
where T110.PROJECTID = "P20211013000000001"
	and T110.DELFLG = "0"
order by T110.SEQ ASC 