#DB選択
USE DB001_PMDB;

#T100
DROP TABLE T110_TASK;
CREATE TABLE T110_TASK (
	PROJECTID char(18) NOT NULL,
	SEQ int NOT NULL,
	TASKTITLE varchar(256),
	TASKDETAIL varchar(1024),
	NAIYO TEXT(65535),
	TANTSH varchar(256),
	KIHYO_DATE DATETIME,
	KIGN_DATE DATETIME,
	TASKSTATUS char(1),
	CRTSRV char(5) NOT NULL,
	CRTUSR char(18) NOT NULL,
	CRTDATE DATETIME NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR char(18) NOT NULL,
	UPDDATE DATETIME NOT NULL,
	DELFLG char(1) NOT NULL,
	PRIMARY KEY(PROJECTID,SEQ)
);
